# Generated by Django 4.1.13 on 2023-11-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=100)),
                ('prediction', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
    ]
